[project]
name = "ml-final-cifar-100"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.8.0",
    "wandb>=0.21.1",
]
