name: sweep_effnetv2_l
method: random
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  model:
    distribution: constant
    value: effnetv2_l
  loss_fn:
    distribution: constant
    value: cross_entropy
  epochs:
    distribution: constant
    value: 30
  freeze_pretrained:
    distribution: constant
    value: False
  weight_init:
    distribution: constant
    value: True
  patience:
    distribution: constant
    value: 3
  lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.05
  batch_size:
    distribution: categorical
    values: [64, 128, 256]
  optimizer:
    distribution: categorical
    values: [adam, sgd]