name: sweep_resnet
method: random
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  model:
    distribution: constant
    value: resnet
  loss_fn:
    distribution: constant
    value: cross_entropy
  epochs:
    distribution: int_uniform
    min: 5
    max: 10
  lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.01
  batch_size:
    distribution: categorical
    values: [64, 128, 256]
  optimizer:
    distribution: categorical
    values: [adam, sgd]
  freeze_pretrained:
    distribution: categorical
    values: [True, False]
  weight_init:
    distribution: categorical
    values: [True, False]
  patience:
    distribution: constant
    value: 3